version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
- package-ecosystem: npm
  directory: "/backend/obscenecommits"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
