name: Build and Deploy Obscene Commits Backend

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: obscenecommits # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'backend/obscenecommits' # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '14.x'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: build_obscenecommits

    steps:
    - uses: actions/checkout@main

    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules-backend
      with:
        path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles(format('{0}/package-lock.json', env.AZURE_FUNCTIONAPP_PACKAGE_PATH)) }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    
    - run: npm ci
      working-directory: ./${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

    - name: 'Build functions'
      run: npm run build --if-present
      working-directory: ./${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

    - name: 'Deploy Azure Functions'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }} 
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

    - uses: actions/upload-artifact@v2
      with:
        name: dist-obscenecommits
        path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/dist
