name: Pull Request Cleanup

on:
  pull_request:
    types: [closed]

jobs:
  remove_frontend_deployment:
    runs-on: ubuntu-latest
    environment: build_frontend

    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true
    
    - name: Delete blobs
      uses: azure/powershell@v1
      with:
        azPSVersion: latest
        inlineScript: |
          Set-AzCurrentStorageAccount -ResourceGroupName ${{ secrets.RESOURCE_GROUP_NAME }} -Name ${{ secrets.STORAGE_ACCOUNT_NAME }}
          Get-AzStorageBlob -Container '$web' -Prefix "${{ github.head_ref }}" | Remove-AzStorageBlob
