name: Build and Deploy Website

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache node modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - run: npm ci

    - run: npm run build:prod

    - uses: actions/upload-artifact@v2
      with:
        name: dist
        path: _site/

  deploy:
    needs: build
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: dist
        path: _site/

    - uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true
    
    - name: Upload to blob storage
      uses: azure/powershell@v1
      with:
        azPSVersion: latest
        inlineScript: |
          $staticAssetCacheControl = "public, max-age=31536000, immutable"
          $revalidateAssetCacheControl = "no-cache"
          $cacheControlHeaders = @{
            ".css" = $staticAssetCacheControl;
            ".js" = $staticAssetCacheControl;
            ".woff" = $staticAssetCacheControl;
            ".woff2" = $staticAssetCacheControl;
            ".jpg" = $staticAssetCacheControl;
            ".png" = $staticAssetCacheControl;
            ".svg" = $staticAssetCacheControl;
            ".html" = $revalidateAssetCacheControl;
          }
          cd _site
          Set-AzCurrentStorageAccount -ResourceGroupName ${{ secrets.RESOURCE_GROUP_NAME }} -Name ${{ secrets.STORAGE_ACCOUNT_NAME }}
          Get-ChildItem -File -Recurse |
            Foreach-Object {
              Write-Output $_.fullName
              Write-Output $_.extension
              $cacheControlHeader = if($cacheControlHeaders.containsKey($_.extension)) { $cacheControlHeaders[$_.extension] } else { $revalidateAssetCacheControl }
              $properties = @{ CacheControl = $cacheControlHeader }
              $relativePath = $_ | Resolve-Path -Relative
              Set-AzStorageBlobContent -File $_.fullName -Blob $relativePath -Container '$web' -properties $properties -Force
            }
          # az storage blob upload-batch -s _site/ -d \$web --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} --auth-mode login

